version: "3.8"

volumes:
    ai_models:
        external: true

services:
    env:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            # named volume mapped into the container
            - ai_models:/simple-transformers/docker-volume/
            # bind/host volume for development
            - .:/simple-transformers
        ports:
            - "8888:8888" # host:container exposed port for web applications
        environment:
            - NVIDIA_VISIBLE_DEVICES=all